<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Licence\Model;

use Licence\Model\Base\Licence as BaseLicence;

/**
 * Class Licence
 * @package Licence\Model
 */
class Licence extends BaseLicence
{
}
