<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Licence\Action;

use Licence\Action\Base\LicenceAction as  BaseLicenceAction;

/**
 * Class LicenceAction
 * @package Licence\Action
 */
class LicenceAction extends BaseLicenceAction
{
}
