<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Licence\Form\Type;

use Licence\Form\Type\Base\LicenceIdType as BaseLicenceIdType;

/**
 * Class Licence
 * @package Licence\Form
 */
class LicenceIdType extends BaseLicenceIdType
{
}
