<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Licence;

use Thelia\Module\BaseModule;
use Propel\Runtime\Connection\ConnectionInterface;
use Thelia\Install\Database;
use Thelia\Model\Message;
use Thelia\Model\MessageQuery;

/**
 * Class Licence
 * @package Licence
 */
class Licence extends BaseModule
{
    const MESSAGE_DOMAIN = "licence";
    const ROUTER = "router.licence";

    public function postActivation(ConnectionInterface $con = null)
    {
        $database = new Database($con);
        $database->insertSql(null, [__DIR__ . "/Config/create.sql", __DIR__ . "/Config/insert.sql"]);

        // create new message
        if (null === MessageQuery::create()->findOneByName('mail_licence')) {
            $message = new Message();
            $message
                ->setName('mail_licence')
                ->setHtmlTemplateFileName('licence-mail.html')
                ->setHtmlLayoutFileName('')
                ->setlocale('fr_FR')
                ->setSubject('Votre numero de licence')
                ->setTitle('Email envoie numero de licence')
                ->setSecured(0)
                ->save();


        }

    }
}
