<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Licence\Event\Module\Base;

/**
 * Class LicenceEvents
 * @package Licence\Event\Module\Base
 * @author TheliaStudio
 */
class LicenceEvents
{
    const LICENCE_CREATE = "action.Licence.create";
    const LICENCE_UPDATE = "action.Licence.update";
    const LICENCE_DELETE = "action.Licence.delete";
}
