<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Licence\Event;

use Licence\Event\Base\LicenceEvent as BaseLicenceEvent;

/**
 * Class LicenceEvent
 * @package Licence\Event
 */
class LicenceEvent extends BaseLicenceEvent
{
}
