<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Licence\Event;

use Licence\Event\Base\LicenceEvents as BaseLicenceEvents;

/**
 * Class LicenceEvents
 * @package Licence\Event
 */
class LicenceEvents extends BaseLicenceEvents
{
}
