<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Licence\Form\Base;

use Licence\Form\LicenceCreateForm as ChildLicenceCreateForm;
use Licence\Form\Type\LicenceIdType;

/**
 * Class LicenceForm
 * @package Licence\Form
 * @author TheliaStudio
 */
class LicenceUpdateForm extends ChildLicenceCreateForm
{
    const FORM_NAME = "Licence_update";

    public function buildForm()
    {
        parent::buildForm();

        $this->formBuilder
            ->add("id", LicenceIdType::TYPE_NAME)
        ;
    }
}
