<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Licence\Loop;

use Licence\Loop\Base\Licence as BaseLicenceLoop;

/**
 * Class Licence
 * @package Licence\Loop
 */
class Licence extends BaseLicenceLoop
{
    /**
     * You may now add your own logic
     */
}
