<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Licence\Form;

use Licence\Form\Base\LicenceCreateForm as BaseLicenceCreateForm;

/**
 * Class LicenceCreateForm
 * @package Licence\Form
 */
class LicenceCreateForm extends BaseLicenceCreateForm
{
    public function getTranslationKeys()
    {
        return array(
            "order_id" => "Order id",
            "customer_id" => "Customer id",
            "product_id" => "Product id",
            "product_key" => "Product key",
            "active_machine" => "Active machine",
            "expiration_date" => "Expiration date",
        );
    }
}
