<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Licence\Form;

use Licence\Form\Base\LicenceUpdateForm as BaseLicenceUpdateForm;

/**
 * Class LicenceUpdateForm
 * @package Licence\Form
 */
class LicenceUpdateForm extends BaseLicenceUpdateForm
{
    public function getTranslationKeys()
    {
        return array(
            "id" => "id",
            "order_id" => "order_id",
            "customer_id" => "customer_id",
            "product_id" => "product_id",
            "product_key" => "product_key",
            "active_machine" => "active_machine",
            "expiration_date" => "expiration_date",
        );
    }
}
