<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Licence\Loop\Base;

use Propel\Runtime\ActiveQuery\Criteria;
use Thelia\Core\Template\Element\BaseLoop;
use Thelia\Core\Template\Element\LoopResult;
use Thelia\Core\Template\Element\LoopResultRow;
use Thelia\Core\Template\Element\PropelSearchLoopInterface;
use Thelia\Core\Template\Loop\Argument\Argument;
use Thelia\Core\Template\Loop\Argument\ArgumentCollection;
use Thelia\Type\BooleanOrBothType;
use Licence\Model\LicenceQuery;

/**
 * Class Licence
 * @package Licence\Loop\Base
 * @author TheliaStudio
 */
class Licence extends BaseLoop implements PropelSearchLoopInterface
{
    protected $versionable = true;

    /**
     * @param LoopResult $loopResult
     *
     * @return LoopResult
     */
    public function parseResults(LoopResult $loopResult)
    {
        /** @var \Licence\Model\Licence $entry */
        foreach ($loopResult->getResultDataCollection() as $entry) {
            $row = new LoopResultRow($entry);

            $row
                ->set("ID", $entry->getId())
                ->set("ORDER_ID", $entry->getOrderId())
                ->set("CUSTOMER_ID", $entry->getCustomerId())
                ->set("PRODUCT_ID", $entry->getProductId())
                ->set("PRODUCT_KEY", $entry->getProductKey())
                ->set("ACTIVE_MACHINE", $entry->getActiveMachine())
                ->set("EXPIRATION_DATE", $entry->getExpirationDate())
            ;

            $this->addMoreResults($row, $entry);

            $loopResult->addRow($row);
        }

        return $loopResult;
    }

    /**
     * Definition of loop arguments
     *
     * example :
     *
     * public function getArgDefinitions()
     * {
     *  return new ArgumentCollection(
     *
     *       Argument::createIntListTypeArgument('id'),
     *           new Argument(
     *           'ref',
     *           new TypeCollection(
     *               new Type\AlphaNumStringListType()
     *           )
     *       ),
     *       Argument::createIntListTypeArgument('category'),
     *       Argument::createBooleanTypeArgument('new'),
     *       ...
     *   );
     * }
     *
     * @return \Thelia\Core\Template\Loop\Argument\ArgumentCollection
     */
    protected function getArgDefinitions()
    {
        return new ArgumentCollection(
            Argument::createIntListTypeArgument("id"),
            Argument::createIntListTypeArgument("order_id"),
            Argument::createIntListTypeArgument("customer_id"),
            Argument::createIntListTypeArgument("product_id"),
            Argument::createEnumListTypeArgument(
                "order",
                [
                    "id",
                    "id-reverse",
                    "order_id",
                    "order_id-reverse",
                    "customer_id",
                    "customer_id-reverse",
                    "product_id",
                    "product_id-reverse",
                    "product_key",
                    "product_key-reverse",
                    "active_machine",
                    "active_machine-reverse",
                    "expiration_date",
                    "expiration_date-reverse",
                ],
                "id"
            )
        );
    }

    /**
     * this method returns a Propel ModelCriteria
     *
     * @return \Propel\Runtime\ActiveQuery\ModelCriteria
     */
    public function buildModelCriteria()
    {
        $query = new LicenceQuery();

        if (null !== $id = $this->getId()) {
            $query->filterById($id);
        }

        if (null !== $order_id = $this->getOrderId()) {
            $query->filterByOrderId($order_id);
        }

        if (null !== $customer_id = $this->getCustomerId()) {
            $query->filterByCustomerId($customer_id);
        }

        if (null !== $product_id = $this->getProductId()) {
            $query->filterByProductId($product_id);
        }

        foreach ($this->getOrder() as $order) {
            switch ($order) {
                case "id":
                    $query->orderById();
                    break;
                case "id-reverse":
                    $query->orderById(Criteria::DESC);
                    break;
                case "order_id":
                    $query->orderByOrderId();
                    break;
                case "order_id-reverse":
                    $query->orderByOrderId(Criteria::DESC);
                    break;
                case "customer_id":
                    $query->orderByCustomerId();
                    break;
                case "customer_id-reverse":
                    $query->orderByCustomerId(Criteria::DESC);
                    break;
                case "product_id":
                    $query->orderByProductId();
                    break;
                case "product_id-reverse":
                    $query->orderByProductId(Criteria::DESC);
                    break;
                case "product_key":
                    $query->orderByProductKey();
                    break;
                case "product_key-reverse":
                    $query->orderByProductKey(Criteria::DESC);
                    break;
                case "active_machine":
                    $query->orderByActiveMachine();
                    break;
                case "active_machine-reverse":
                    $query->orderByActiveMachine(Criteria::DESC);
                    break;
                case "expiration_date":
                    $query->orderByExpirationDate();
                    break;
                case "expiration_date-reverse":
                    $query->orderByExpirationDate(Criteria::DESC);
                    break;
            }
        }

        return $query;
    }

    protected function addMoreResults(LoopResultRow $row, $entryObject)
    {
    }
}
