<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Licence\Event\Module;

use Licence\Event\Module\Base\LicenceEvents as BaseLicenceEvents;

/**
 * Class LicenceEvents
 * @package Licence\Event\Module
 * @author TheliaStudio
 */
class LicenceEvents extends BaseLicenceEvents
{
}
