<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Licence\Controller\Base;

use Symfony\Component\HttpFoundation\RedirectResponse;
use Thelia\Controller\Admin\AbstractCrudController;
use Thelia\Core\Security\Resource\AdminResources;
use Thelia\Tools\URL;
use Licence\Event\LicenceEvent;
use Licence\Event\LicenceEvents;
use Licence\Model\LicenceQuery;

/**
 * Class LicenceController
 * @package Licence\Controller\Base
 * @author TheliaStudio
 */
class LicenceController extends AbstractCrudController
{
    public function __construct()
    {
        parent::__construct(
            "Licence",
            "id",
            "order",
            AdminResources::MODULE,
            LicenceEvents::CREATE,
            LicenceEvents::UPDATE,
            LicenceEvents::DELETE,
            null,
            null,
            "Licence"
        );
    }

    /**
     * Return the creation form for this object
     */
    protected function getCreationForm()
    {
        return $this->createForm("Licence.create");
    }

    /**
     * Return the update form for this object
     */
    protected function getUpdateForm($data = array())
    {
        if (!is_array($data)) {
            $data = array();
        }

        return $this->createForm("Licence.update", "form", $data);
    }

    /**
     * Hydrate the update form for this object, before passing it to the update template
     *
     * @param mixed $object
     */
    protected function hydrateObjectForm($object)
    {
        $data = array(
            "id" => $object->getId(),
            "order_id" => $object->getOrderId(),
            "customer_id" => $object->getCustomerId(),
            "product_id" => $object->getProductId(),
            "product_key" => $object->getProductKey(),
            "active_machine" => $object->getActiveMachine(),
            "expiration_date" => $object->getExpirationDate(),
        );

        return $this->getUpdateForm($data);
    }

    /**
     * Creates the creation event with the provided form data
     *
     * @param mixed $formData
     * @return \Thelia\Core\Event\ActionEvent
     */
    protected function getCreationEvent($formData)
    {
        $event = new LicenceEvent();

        $event->setOrderId($formData["order_id"]);
        $event->setCustomerId($formData["customer_id"]);
        $event->setProductId($formData["product_id"]);
        $event->setProductKey($formData["product_key"]);
        $event->setActiveMachine($formData["active_machine"]);
        $event->setExpirationDate($formData["expiration_date"]);

        return $event;
    }

    /**
     * Creates the update event with the provided form data
     *
     * @param mixed $formData
     * @return \Thelia\Core\Event\ActionEvent
     */
    protected function getUpdateEvent($formData)
    {
        $event = new LicenceEvent();

        $event->setId($formData["id"]);
        $event->setOrderId($formData["order_id"]);
        $event->setCustomerId($formData["customer_id"]);
        $event->setProductId($formData["product_id"]);
        $event->setProductKey($formData["product_key"]);
        $event->setActiveMachine($formData["active_machine"]);
        $event->setExpirationDate($formData["expiration_date"]);

        return $event;
    }

    /**
     * Creates the delete event with the provided form data
     */
    protected function getDeleteEvent()
    {
        $event = new LicenceEvent();

        $event->setId($this->getRequest()->request->get("Licence_id"));

        return $event;
    }

    /**
     * Return true if the event contains the object, e.g. the action has updated the object in the event.
     *
     * @param mixed $event
     */
    protected function eventContainsObject($event)
    {
        return null !== $this->getObjectFromEvent($event);
    }

    /**
     * Get the created object from an event.
     *
     * @param mixed $event
     */
    protected function getObjectFromEvent($event)
    {
        return $event->getLicence();
    }

    /**
     * Load an existing object from the database
     */
    protected function getExistingObject()
    {
        return LicenceQuery::create()
            ->findPk($this->getRequest()->query->get("Licence_id"))
        ;
    }

    /**
     * Returns the object label form the object event (name, title, etc.)
     *
     * @param mixed $object
     */
    protected function getObjectLabel($object)
    {
        return '';
    }

    /**
     * Returns the object ID from the object
     *
     * @param mixed $object
     */
    protected function getObjectId($object)
    {
        return $object->getId();
    }

    /**
     * Render the main list template
     *
     * @param mixed $currentOrder , if any, null otherwise.
     */
    protected function renderListTemplate($currentOrder)
    {
        $this->getParser()
            ->assign("order", $currentOrder)
        ;

        return $this->render("Licences");
    }

    /**
     * Render the edition template
     */
    protected function renderEditionTemplate()
    {
        $this->getParserContext()
            ->set(
                "Licence_id",
                $this->getRequest()->query->get("Licence_id")
            )
        ;

        return $this->render("Licence-edit");
    }

    /**
     * Must return a RedirectResponse instance
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    protected function redirectToEditionTemplate()
    {
        $id = $this->getRequest()->query->get("Licence_id");

        return new RedirectResponse(
            URL::getInstance()->absoluteUrl(
                "/admin/module/Licence/Licence/edit",
                [
                    "Licence_id" => $id,
                ]
            )
        );
    }

    /**
     * Must return a RedirectResponse instance
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    protected function redirectToListTemplate()
    {
        return new RedirectResponse(
            URL::getInstance()->absoluteUrl("/admin/module/Licence/Licence")
        );
    }
}
