<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Licence\Event\Base;

use Licence\Event\Module\LicenceEvents as ChildLicenceEvents;

/*
 * Class LicenceEvents
 * @package Licence\Event\Base
 * @author TheliaStudio
 */
class LicenceEvents
{
    const CREATE = ChildLicenceEvents::LICENCE_CREATE;
    const UPDATE = ChildLicenceEvents::LICENCE_UPDATE;
    const DELETE = ChildLicenceEvents::LICENCE_DELETE;
}
