<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Licence\Form\Type\Base;

use Thelia\Core\Form\Type\Field\AbstractIdType;
use Licence\Model\LicenceQuery;

/**
 * Class Licence
 * @package Licence\Form\Base
 * @author TheliaStudio
 */
class LicenceIdType extends AbstractIdType
{
    const TYPE_NAME = "Licence_id";

    protected function getQuery()
    {
        return new LicenceQuery();
    }

    public function getName()
    {
        return static::TYPE_NAME;
    }
}
