<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Licence\Controller;

use Licence\Controller\Base\LicenceController as BaseLicenceController;

/**
 * Class LicenceController
 * @package Licence\Controller
 */
class LicenceController extends BaseLicenceController
{
}
